### ISSUE TITLE
Large installation file?

### ISSUE THREAD

**Issue by MartinW2** [KatsuteDev/Stop-Chrome#255]
### Feature

This probably does not qualify as a feature request - however, I am just wondering why a small (very useful!) tool like this requires an installation executable of 95 MB? The sources are tiny compared to this size. Are there so many depending libraries that need to be involved/included?
I am lazy, I know. I did not dig deeper into this.  Just a stupid noob question. Maybe it will get an answer, or there is another way of packaging that will result in significantly smaller installation file. Feel free to simply close this if it's not worth a reply. Thank you.

### Reason

Large installation file may prevent people from downloading or using the tool - especially if there are virus warnings (despite of mentioning these are false positives).

**Comment by Katsute** [comment]
This is an electron app, it installs all resources necessary to run chromium.

**Comment by MartinW2** [comment]
Thank you for clarification, I was not aware of electron apps and their pro's and con's (learned now).
